import { ShieldCheck, Info, Lock, Key } from 'lucide-react';

export function PrivacyPolicy() {
  return (
    <div className="p-8 max-w-3xl mx-auto space-y-6 font-sans">
      <div className="flex items-center space-x-3 text-red-500 mb-2 border-b border-zinc-800 pb-4">
        <ShieldCheck className="h-8 w-8" />
        <h1 className="text-xl font-bold font-mono tracking-wider text-white">PRIVACY POLICY STATEMENT</h1>
      </div>
      
      <p className="text-xs text-zinc-500 uppercase tracking-widest font-mono">Effective: August 2026</p>
      
      <div className="space-y-4 text-sm text-zinc-300 leading-relaxed">
        <h3 className="font-bold text-white font-mono uppercase">1. Zero Persistent Audio Storage</h3>
        <p>
          By default, VOICEGUARD does not cache, write, or permanently store raw audio signals processed via live microphone streams or uploaded files. All incoming PCM streams are loaded into a temporary circular RAM buffer and immediately overwritten after feature vector extraction is complete.
        </p>

        <h3 className="font-bold text-white font-mono uppercase">2. Configurable Cache Retention</h3>
        <p>
          If data validation logging is explicitly enabled by the system Administrator for model debugging, files are deleted automatically within the configured retention duration window (e.g. 7 days). Users can manually flush their session logs at any time via the History Console.
        </p>

        <h3 className="font-bold text-white font-mono uppercase">3. Encryption & Access Controls</h3>
        <p>
          Metadata features and analysis risk summaries are stored securely in SQL tables protected behind OAuth2 JWT tokens. No raw client speech data is shared with external machine learning clouds.
        </p>
      </div>
    </div>
  );
}

export function TermsOfService() {
  return (
    <div className="p-8 max-w-3xl mx-auto space-y-6 font-sans">
      <div className="flex items-center space-x-3 text-red-500 mb-2 border-b border-zinc-800 pb-4">
        <ShieldCheck className="h-8 w-8" />
        <h1 className="text-xl font-bold font-mono tracking-wider text-white">TERMS OF SERVICE AGREEMENT</h1>
      </div>
      
      <p className="text-xs text-zinc-500 uppercase tracking-widest font-mono">SIH2026 Sandbox License</p>
      
      <div className="space-y-4 text-sm text-zinc-300 leading-relaxed">
        <h3 className="font-bold text-white font-mono uppercase">1. Prototype Sandbox Disclaimer</h3>
        <p>
          VOICEGUARD is designed and distributed as a Smart India Hackathon 2026 prototype (AICTE Problem Statement SIH26104). The risk indexes and spoof probability ratings generated by the models are designed for testing and forensic demonstrations and should not be used as absolute proof of fraud.
        </p>

        <h3 className="font-bold text-white font-mono uppercase">2. User Verification Responsibilities</h3>
        <p>
          Any high-risk financial, executive, or administrative transaction should undergo secondary out-of-band identity checks. VOICEGUARD is not liable for operational decisions made based on AI-assisted telemetry scoring.
        </p>
      </div>
    </div>
  );
}

export function SecurityBrief() {
  return (
    <div className="p-8 max-w-3xl mx-auto space-y-6 font-sans">
      <div className="flex items-center space-x-3 text-red-500 mb-2 border-b border-zinc-800 pb-4">
        <Lock className="h-8 w-8" />
        <h1 className="text-xl font-bold font-mono tracking-wider text-white">SECURITY & INGESTION BRIEF</h1>
      </div>
      
      <p className="text-xs text-zinc-500 uppercase tracking-widest font-mono">Forensics Architecture Standards</p>
      
      <div className="space-y-4 text-sm text-zinc-300 leading-relaxed font-mono">
        <h3 className="font-bold text-white uppercase">1. Network Rate Limiting</h3>
        <p className="text-xs text-zinc-400">
          Enforces maximum payload limits on batch file uploads (capped at 15MB) and implements strict rate limits to prevent denial-of-service on WebSocket endpoints.
        </p>

        <h3 className="font-bold text-white uppercase">2. Sandbox Execution Policies</h3>
        <p className="text-xs text-zinc-400">
          Backend server nodes execute ML classifiers in isolated sub-processes. Uploaded files undergo automatic mime-type validation to block execution of binary script code masquerading as sound signals.
        </p>

        <h3 className="font-bold text-white uppercase">3. Telephony Trunk Protections</h3>
        <p className="text-xs text-zinc-400">
          Telephony ingestion adapters authenticate incoming SIP redirection trunks using pre-shared token handshakes. Twilio payload parameters are decoded in-memory and validation-checked before feeding the risk scoring engine.
        </p>
      </div>
    </div>
  );
}
